src/AirBench/AirBench/Models/Bench.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirBench.Models
{
    public class Bench
    {
        public Bench()
        {
            Reviews = new List<Review>();
        }

        public int Id { get; set; }
        [Required]
        public string Description { get; set; }
        public int NumberOfSeats { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public int UserId { get; set; }
        public User User { get; set; }

        public List<Review> Reviews { get; set; }

        public string ShortDescription
        {
            get
            {
                string description = Description;
                string shortDescription = string.Empty;

                // Make sure that we have a description...
                if (!string.IsNullOrWhiteSpace(description))
                {
                    // Get a collection of the words in the description.
                    var words = description
                        .Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

                    // If we have more than 10 words
                    // then take the first 10 and add "..." to the end
                    // otherwise just use the description as is. 
                    if (words.Length > 10)
                    {
                        shortDescription = string.Join(" ", words.Take(10)) + "...";
                    }
                    else
                    {
                        shortDescription = description;
                    }
                }

                return shortDescription;
            }
        }

        public double? AverageRating
        {
            get
            {
                if (Reviews.Count > 0)
                {
                    return Math.Round(Reviews.Average(r => r.Rating), 1);

                    //decimal sum = 0;
                    //foreach (var review in Reviews)
                    //{
                    //    sum += review.Rating;
                    //}
                    //return Math.Round(sum / Reviews.Count, 1);
                }
                else
                {
                    return null;
                }
            }
        }
    }
}

src/AirBench/AirBench/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirBench.Models
{
    public class Review
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        [Required]
        public string Comment { get; set; }
        public DateTimeOffset CreatedOn { get; set; }

        public int BenchId { get; set; }
        public Bench Bench { get; set; }

        public int UserId { get; set; }
        public User User { get; set; }
    }
}

src/AirBench/AirBench/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AirBench.Models
{
    public class User
    {
        public User()
        {
            Benches = new List<Bench>();
            Reviews = new List<Review>();
        }

        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string HashedPassword { get; set; }

        public List<Bench> Benches { get; set; }
        public List<Review> Reviews { get; set; }

        public string DisplayName
        {
            get
            {
                return $"{FirstName} {LastName.Substring(0, 1)}.";
            }
        }
    }
}

src/AirBench/AirBench/Controllers/BenchesController.cs
using AirBench.FormModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AirBench.Controllers
{
    public class BenchesController : Controller
    {
        public ActionResult Create()
        {
            var formModel = new CreateBench();
            return View(formModel);
        }
    }
}

src/AirBench/AirBench/Controllers/HomeController.cs
using AirBench.Data;
using AirBench.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AirBench.Controllers
{
    public class HomeController : Controller
    {
        private IBenchRepository repository;

        public HomeController(IBenchRepository repository)
        {
            this.repository = repository;
        }

        public async Task<ActionResult> Index()
        {
            ViewBag.BaseApiUrl = ConfigurationManager.AppSettings["BaseApiUrl"];

            var benches = await repository.GetList();
            return View(benches);
        }
    }
}

src/AirBench/AirBench/Views/Benches/Create.cshtml
@model AirBench.FormModels.CreateBench

@{
    ViewBag.Title = "Create Bench";
}

<h2>Create Bench</h2>

@using (Html.BeginForm("Create", "Benches", FormMethod.Post, new { id = "CreateBenchForm", @class = "manage-submit-button" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfSeats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfSeats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfSeats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Temp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Temp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Temp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input id="CreateBenchButton" type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

src/AirBench/AirBench/Views/Home/Index.cshtml
@model List<AirBench.Models.Bench>

@{
    ViewBag.Title = "Home";
}

<h2>Home</h2>

<p>@Html.ActionLink("Create a Bench", "Create", "Benches")</p>

<form id="bench-filtering" class="form-inline">
    <div class="form-group">
        <label for="minNumberOfSeats">Min:</label>
        <input type="number" id="minNumberOfSeats" class="form-control" />
    </div>
    <div class="form-group">
        <label for="maxNumberOfSeats">Max:</label>
        <input type="number" id="maxNumberOfSeats" class="form-control" />
    </div>
</form>

<div id="benches"></div>

<script>
    const airBenchConfig = {
        baseApiUrl: '@ViewBag.BaseApiUrl'
    };
</script>
<script src="~/Scripts/App/data.js"></script>
<script src="~/Scripts/App/benches-html.js"></script>
<script src="~/Scripts/App/main.js"></script>

src/AirBench/AirBench/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AirBench</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AirBench", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AirBench</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/App/form-button-manager.js"></script>
</body>
</html>